export enum NotificationType {
  NEW_INFLUENCER_REVIEW = 'NEW_INFLUENCER_REVIEW',
  ACCOUNT_APPROVED = 'ACCOUNT_APPROVED',
  ACCOUNT_REJECTED = 'ACCOUNT_REJECTED',
  CAMPAIGN_SUBMITTED_FOR_REVIEW = 'CAMPAIGN_SUBMITTED_FOR_REVIEW',
  CAMPAIGN_APPROVED = 'CAMPAIGN_APPROVED',
  CAMPAIGN_REJECTED = 'CAMPAIGN_REJECTED',
  CAMPAIGN_INVITATION = 'CAMPAIGN_INVITATION',
  CAMPAIGN_PENDING_MINIMUM = 'CAMPAIGN_PENDING_MINIMUM',
  CAMPAIGN_AUTO_DISCARDED = 'CAMPAIGN_AUTO_DISCARDED',
}
